import type { Opportunity, OpportunityCategoryMeta } from "@/types";

export const opportunityCategories: OpportunityCategoryMeta[] = [
  {
    id: "all",
    label: "All opportunities",
    description: "Everything a founder can act on now.",
  },
  {
    id: "hackathon",
    label: "Hackathons",
    description: "Build sprints, bounties, and shipping competitions.",
  },
  {
    id: "accelerator",
    label: "Accelerators",
    description: "Cohorts, venture studios, and mentor-led programs.",
  },
  {
    id: "funding",
    label: "Funding",
    description: "Non-dilutive capital, credits, and grant windows.",
  },
  {
    id: "incentive",
    label: "Incentives",
    description: "Startup credits, software discounts, banking perks, and runway savers.",
  },
  {
    id: "conference",
    label: "Upcoming events",
    description: "Founder conferences, summits, and investor rooms.",
  },
  {
    id: "competition",
    label: "Competitions",
    description: "Pitch contests and startup prize tracks.",
  },
  {
    id: "launch",
    label: "Launch channels",
    description: "Channels for shipping, feedback, and distribution.",
  },
  {
    id: "talent",
    label: "Talent network",
    description: "Interns, new grads, and startup job channels.",
  },
  {
    id: "mentor",
    label: "Mentor network",
    description: "Operator advice, office hours, and expert networks.",
  },
  {
    id: "investor",
    label: "Investor network",
    description: "Investors, directories, and sector-specific funding paths.",
  },
  {
    id: "forum",
    label: "Forums",
    description: "Communities where founders ask, test, and recruit.",
  },
  {
    id: "fellowship",
    label: "Fellowships",
    description: "Founder fellowships, operator programs, and learning cohorts.",
  },
  {
    id: "news",
    label: "News",
    description: "Market signals, ecosystem updates, and trend alerts.",
  },
];

export const opportunities: Opportunity[] = [
  {
    id: "gemini-xprize",
    title: "Build with Gemini XPRIZE",
    organization: "XPRIZE x Google",
    category: "hackathon",
    format: "Online",
    location: "Global",
    sectors: ["AI", "Consumer", "Enterprise"],
    audience: "Founders and builders turning Gemini prototypes into real products.",
    summary:
      "A 90-day global builder competition focused on shipping real AI applications and businesses with Google Gemini.",
    deadline: "2026-08-17",
    value: "$2,000,000 prize pool",
    cost: "Free",
    sourceName: "HackList",
    sourceUrl: "https://hacklist.io/",
    actionLabel: "Apply",
    tags: ["AI", "Online", "Prize"],
    trustSignal: "Scraped from HackList spotlight on June 20, 2026.",
    priority: "soon",
    featured: true,
  },
  {
    id: "qvac-edge-ai",
    title: "QVAC Edge AI Hackathon",
    organization: "Tether",
    category: "hackathon",
    format: "Online",
    location: "Global",
    sectors: ["AI", "Infrastructure", "Privacy"],
    audience: "Teams building local-first AI, on-device inference, RAG, and private AI systems.",
    summary:
      "An edge AI hackathon centered on local-first systems, privacy-preserving AI applications, and on-device intelligence.",
    deadline: "2026-06-21",
    value: "$21,000 USDT",
    cost: "Free",
    sourceName: "HackList",
    sourceUrl: "https://hacklist.io/",
    actionLabel: "Apply",
    tags: ["AI", "Edge", "Closing soon"],
    trustSignal: "HackList listed it as closing in 1 day on June 20, 2026.",
    priority: "urgent",
  },
  {
    id: "launchhacks-v",
    title: "LaunchHacks V",
    organization: "LaunchHacks",
    category: "hackathon",
    format: "Online",
    location: "Global",
    sectors: ["AI", "Product", "Consumer"],
    audience: "Founders who want a deadline for shipping a real product and launch story.",
    summary:
      "A product-first online hackathon built around execution, creativity, and shipping usable AI products.",
    deadline: "2026-06-22",
    value: "$17,575 prize pool",
    cost: "Free",
    sourceName: "HackList",
    sourceUrl: "https://hacklist.io/",
    actionLabel: "Apply",
    tags: ["AI", "Product", "Online"],
    trustSignal: "HackList listed it as closing in 2 days on June 20, 2026.",
    priority: "urgent",
  },
  {
    id: "sui-overflow-2026",
    title: "Sui Overflow 2026",
    organization: "Sui Foundation",
    category: "hackathon",
    format: "Online",
    location: "Global",
    sectors: ["Web3", "Consumer crypto", "Infrastructure"],
    audience: "Teams building consumer crypto, infrastructure tooling, and AI integrations on Sui.",
    summary:
      "Sui's flagship global hackathon for builders working on scalable blockchain products and adjacent AI workflows.",
    deadline: "2026-06-30",
    value: "$1,000,000+ prize pool",
    cost: "Free",
    sourceName: "HackList",
    sourceUrl: "https://hacklist.io/",
    actionLabel: "Apply",
    tags: ["Web3", "Online", "Large prize"],
    trustSignal: "HackList listed it as closing in 10 days on June 20, 2026.",
    priority: "soon",
  },
  {
    id: "slack-agent-builder",
    title: "Slack Agent Builder Challenge",
    organization: "Slack x Salesforce x Devpost",
    category: "hackathon",
    format: "Online",
    location: "Global",
    sectors: ["AI", "DevTools", "Enterprise"],
    audience: "Teams building Slack agents, MCP integrations, workflow automations, or real-time search experiences.",
    summary:
      "A builder challenge for AI-powered Slack agents with promotion across the Slack ecosystem and a Dreamforce path.",
    deadline: "2026-07-13",
    value: "$42,000 prize pool",
    cost: "Free",
    sourceName: "HackList",
    sourceUrl: "https://hacklist.io/",
    actionLabel: "Apply",
    tags: ["AI agents", "MCP", "Devpost"],
    trustSignal: "HackList listed it as closing in 23 days on June 20, 2026.",
    priority: "soon",
  },
  {
    id: "revenuecat-shipaton-2026",
    title: "RevenueCat Shipaton 2026",
    organization: "RevenueCat",
    category: "hackathon",
    format: "Online",
    location: "Global",
    sectors: ["Mobile", "iOS", "Android", "Consumer apps"],
    audience: "Mobile builders shipping a new app with real monetization, launch assets, and public traction.",
    summary:
      "A global mobile hackathon for shipping a brand-new iOS, Android, or Mac app with RevenueCat-powered purchases during August and September.",
    startDate: "2026-08-01",
    endDate: "2026-09-30",
    value: "$425,000+ in prizes",
    cost: "Free",
    sourceName: "Devpost via X signal",
    sourceUrl: "https://revenuecat-shipaton-2026.devpost.com/",
    actionLabel: "Pre-register",
    tags: ["Mobile", "Build in public", "Students"],
    trustSignal:
      "RevenueCat posted Shipaton organizer applications on X; the official Devpost page lists August 1-September 30, 2026 and $425,000+ in prizes.",
    priority: "soon",
    featured: true,
  },
  {
    id: "raise-summit-hackathon-2026",
    title: "RAISE Summit Hackathon",
    organization: "RAISE Summit",
    category: "hackathon",
    format: "In-person",
    location: "Paris, France",
    sectors: ["AI", "Enterprise", "Infrastructure", "Developer tools"],
    audience: "AI builders, engineers, designers, and founder teams who want to build inside a high-signal summit ecosystem.",
    summary:
      "A Paris AI hackathon run with Cerebral Valley and sponsor tooling, designed around fast demos, summit visibility, and real business problems.",
    startDate: "2026-07-04",
    endDate: "2026-07-05",
    value: "€250,000+ in prizes",
    cost: "Free",
    sourceName: "X post and RAISE",
    sourceUrl: "https://www.raisesummit.com/hackathon",
    actionLabel: "Apply",
    tags: ["AI", "Paris", "Cerebral Valley"],
    trustSignal:
      "Discovered from X partner posts; official RAISE materials describe the hackathon, Paris venue, sponsor tooling, and €250,000+ prize opportunity.",
    priority: "soon",
  },
  {
    id: "shipaton-irl-hosts",
    title: "Host a Shipaton IRL Event",
    organization: "RevenueCat",
    category: "conference",
    format: "Hybrid",
    location: "Campus or local community",
    sectors: ["Mobile", "Student builders", "Community", "Launch"],
    audience: "Campus clubs, developer meetups, indie hacker groups, and local founder communities that can gather mobile builders.",
    summary:
      "RevenueCat is accepting local hosts for Shipaton IRL events, including campus hackathon nights, club workshops, weekend build sprints, and community meetups.",
    value: "Organizer kit, swag, templates, and promotion",
    cost: "Free",
    sourceName: "Shipaton via X signal",
    sourceUrl: "https://www.shipaton.com/events",
    actionLabel: "Apply to host",
    tags: ["Campus", "IRL events", "Community"],
    trustSignal:
      "RevenueCat posted the host call on X; the official Shipaton events page says approved hosts receive physical and digital organizer resources.",
    priority: "watch",
  },
  {
    id: "yc-fall-2026",
    title: "Y Combinator Fall 2026",
    organization: "Y Combinator",
    category: "accelerator",
    format: "In-person",
    location: "San Francisco, CA",
    sectors: ["All sectors", "AI", "B2B", "Consumer"],
    audience: "Founders ready for a three-month company-building batch and investor network.",
    summary:
      "YC is accepting applications for its Fall 2026 batch, which runs from October to December in San Francisco.",
    deadline: "2026-07-27",
    startDate: "2026-10-01",
    endDate: "2026-12-31",
    value: "YC funding and network",
    cost: "Equity",
    sourceName: "Y Combinator",
    sourceUrl: "https://www.ycombinator.com/apply",
    actionLabel: "Apply",
    tags: ["Accelerator", "SF", "Investor network"],
    trustSignal: "Official YC page lists July 27, 2026 at 8pm PT as the on-time deadline.",
    priority: "soon",
    featured: true,
  },
  {
    id: "techstars-network",
    title: "Techstars Accelerators",
    organization: "Techstars",
    category: "accelerator",
    format: "Hybrid",
    location: "Global programs",
    sectors: ["AI health", "Energy", "Food", "Space", "Finance"],
    audience: "Early-stage startups looking for a three-month program, mentorship, capital, and lifelong network access.",
    summary:
      "Techstars maintains a broad accelerator directory across locations and verticals, including Anywhere, AI Health, Space, and climate-adjacent programs.",
    value: "Mentorship + capital access",
    cost: "Equity",
    sourceName: "Techstars",
    sourceUrl: "https://www.techstars.com/accelerators",
    actionLabel: "Find a program",
    tags: ["Accelerator", "Mentors", "Global"],
    trustSignal: "Official Techstars accelerator directory lists active programs and application filters.",
    priority: "watch",
  },
  {
    id: "google-startups-accelerator",
    title: "Google for Startups Accelerator",
    organization: "Google for Startups",
    category: "accelerator",
    format: "Hybrid",
    location: "Regional cohorts",
    sectors: ["AI", "Cloud", "Growth-stage"],
    audience: "Growth-stage startups looking for technical, product, and leadership training from Google teams.",
    summary:
      "Three-month Google accelerator programs tailored by region and sector for startups that can benefit from Google product and technical expertise.",
    value: "Google mentorship and product support",
    cost: "Free",
    sourceName: "Google for Startups",
    sourceUrl: "https://startup.google.com/programs/accelerator/",
    actionLabel: "Explore",
    tags: ["Google", "Technical support", "Growth"],
    trustSignal: "Official Google for Startups accelerator page.",
    priority: "watch",
  },
  {
    id: "sequoia-arc-watch",
    title: "Sequoia Arc",
    organization: "Sequoia Capital",
    category: "accelerator",
    format: "Hybrid",
    location: "Americas and Europe",
    sectors: ["Pre-seed", "Seed", "AI", "All sectors"],
    audience: "Pre-seed and seed founders who want a high-signal Sequoia open call and company-building immersion.",
    summary:
      "Sequoia's Arc path is a recurring open call and company-building program for outlier pre-seed and seed founders.",
    value: "$1,000,000 investment path",
    cost: "Equity",
    sourceName: "Sequoia Arc",
    sourceUrl: "https://www.sequoiacap.com/arc/",
    actionLabel: "Get notified",
    tags: ["Accelerator", "Seed", "Sequoia"],
    trustSignal:
      "Official Sequoia Arc materials describe Arc as a bi-annual open call for pre-seed and seed founders; keep this as a watch item between cohorts.",
    priority: "watch",
  },
  {
    id: "a16z-speedrun-watch",
    title: "a16z speedrun",
    organization: "a16z speedrun",
    category: "accelerator",
    format: "In-person",
    location: "San Francisco, CA",
    sectors: ["AI", "Games", "Consumer", "Entertainment"],
    audience: "Founders building ambitious tech, AI, games, consumer, or entertainment companies that fit a fast cohort model.",
    summary:
      "a16z speedrun invests in new startups and gives founders concentrated operator support, credits, demo day exposure, and fundraising help.",
    value: "Up to $1,000,000 + $7M credits",
    cost: "Equity",
    sourceName: "a16z speedrun",
    sourceUrl: "https://speedrun.a16z.com/apply",
    actionLabel: "Apply for next cohort",
    tags: ["a16z", "SF", "AI"],
    trustSignal:
      "Official speedrun application page says the SR007 deadline passed on May 17, 2026, and late submissions are considered for a future cohort.",
    priority: "watch",
    featured: true,
  },
  {
    id: "spc-founder-fellowship-fall-2026",
    title: "SPC Founder Fellowship",
    organization: "South Park Commons",
    category: "fellowship",
    format: "In-person",
    location: "San Francisco, CA / New York, NY",
    sectors: ["AI", "Developer tools", "Consumer", "All sectors"],
    audience: "Technical founders at the idea, prototype, or early company stage who want dense founder community and partner support.",
    summary:
      "South Park Commons runs founder fellowship cohorts for people moving from conviction to company, with offices, programming, partner support, and capital.",
    startDate: "2026-09-28",
    value: "$400,000 upfront + $600,000 follow-on",
    cost: "Equity",
    sourceName: "South Park Commons",
    sourceUrl: "https://www.southparkcommons.com/founder-fellowship/",
    actionLabel: "Track Fall cohort",
    tags: ["Fellowship", "SPC", "Founder community"],
    trustSignal:
      "Official SPC page says Fall 2026 applications open this summer and the cohort kicks off in late September.",
    priority: "soon",
    featured: true,
  },
  {
    id: "neo-residency-watch",
    title: "Neo Residency + Funding",
    organization: "Neo",
    category: "accelerator",
    format: "In-person",
    location: "San Francisco, CA / Oregon",
    sectors: ["Technical founders", "Students", "AI", "All sectors"],
    audience: "Exceptional technical founders and high-agency student teams looking for capital, mentorship, and a long-term founder network.",
    summary:
      "Neo Residency is a selective startup residency with startup funding, student builder support, compute credits, mentorship, and community access.",
    value: "$750,000 uncapped SAFE + compute credits",
    cost: "Dilutive",
    sourceName: "Neo",
    sourceUrl: "https://neo.com/residency",
    actionLabel: "Track next residency",
    tags: ["Residency", "Students", "Technical founders"],
    trustSignal:
      "Official Neo Residency page says the 2026 residency deadline has passed and points founders to year-round pre-seed or seed funding contact.",
    priority: "watch",
  },
  {
    id: "interior-northeast-icorps-courses",
    title: "Interior Northeast I-Corps Courses",
    organization: "Interior Northeast I-Corps Hub",
    category: "accelerator",
    format: "Hybrid",
    location: "NY, VT, NH, western PA, and WV",
    sectors: ["Research commercialization", "Medtech", "Semiconductors", "Energy"],
    audience: "Researchers, postdocs, graduate students, and startup teams commercializing STEM discoveries.",
    summary:
      "Regional I-Corps courses help research teams test customer discovery, validate markets, and build a stronger path toward commercialization and NSF follow-on programs.",
    deadline: "2026-08-26",
    startDate: "2026-09-21",
    value: "Free customer discovery training",
    cost: "Free",
    sourceName: "Interior Northeast I-Corps Hub",
    sourceUrl: "https://www.in-icorps.org/event-list/",
    actionLabel: "Apply",
    tags: ["I-Corps", "Research", "NSF"],
    trustSignal:
      "Official hub event list shows upcoming September 2026 regional courses with August and September application deadlines.",
    priority: "soon",
  },
  {
    id: "ef-the-bridge",
    title: "Entrepreneur First The Bridge",
    organization: "Entrepreneur First",
    category: "accelerator",
    format: "In-person",
    location: "San Francisco, CA",
    sectors: ["AI", "Technical founders", "Europe to US", "Pre-idea"],
    audience: "Ambitious European technical founders who want to form teams and build from scratch in San Francisco.",
    summary:
      "The Bridge brings selected founders to the Bay Area for an eight-week residency with housing, board, visa support, advisors, credits, and a demo day.",
    value: "Up to $250,000 initial funding + $600,000 credits",
    cost: "Equity",
    sourceName: "Entrepreneur First",
    sourceUrl: "https://www.joinef.com/posts/introducing-the-bridge/",
    actionLabel: "Apply",
    tags: ["Residency", "Co-founder matching", "SF"],
    trustSignal:
      "Official EF announcement says The Bridge runs several cohorts each year, supports 40-50 entrepreneurs per group, and provides housing and board.",
    priority: "watch",
  },
  {
    id: "z-fellows",
    title: "Z Fellows",
    organization: "Z Fellows",
    category: "fellowship",
    format: "Hybrid",
    location: "Online + SF / NYC",
    sectors: ["Consumer", "AI", "Enterprise", "Healthcare", "Fintech"],
    audience: "Early technical thinkers, solo builders, and founder teams who want a one-week forcing function and mentor density.",
    summary:
      "Z Fellows gives builders a focused week to go all in on a project, learn from Silicon Valley mentors, and get investor and founder access.",
    value: "$10,000 investment",
    cost: "Dilutive",
    sourceName: "Z Fellows",
    sourceUrl: "https://www.zfellows.com/",
    actionLabel: "Apply",
    tags: ["Rolling", "Young builders", "Mentors"],
    trustSignal:
      "Official Z Fellows FAQ says applications are reviewed on a rolling basis with no submission deadline.",
    priority: "evergreen",
  },
  {
    id: "anthropic-fellows-program",
    title: "Anthropic Fellows Program",
    organization: "Anthropic",
    organizationDomain: "anthropic.com",
    category: "fellowship",
    format: "Remote",
    location: "Remote / cohort-based",
    sectors: ["AI safety", "AI security", "Research", "Alignment"],
    audience: "Researchers, engineers, and technical builders who want to produce empirical AI safety research with mentorship.",
    summary:
      "Anthropic Fellows is a mentored AI safety research fellowship for technical talent working on empirical projects and public research outputs.",
    value: "$3,850/week stipend + compute support",
    cost: "Free",
    sourceName: "Anthropic",
    sourceUrl: "https://job-boards.greenhouse.io/anthropic/jobs/5023394008",
    actionLabel: "Apply",
    tags: ["AI safety", "Research", "Rolling"],
    trustSignal:
      "Official Anthropic application says fellows are reviewed on a rolling basis for cohorts starting in July 2026 and beyond.",
    priority: "evergreen",
    featured: true,
  },
  {
    id: "a16z-build-fellowships",
    title: "a16z Build Fellowships",
    organization: "a16z Build",
    category: "fellowship",
    format: "Online",
    location: "Global / cohort-based",
    sectors: ["GTM", "Growth", "AI", "Operator network"],
    audience: "Operators, growth engineers, GTM leaders, and founders who want structured learning cohorts inside the a16z network.",
    summary:
      "a16z Build fellowships are eight-week cohorts for world-class leaders to connect, share learnings, and level up around emerging company-building disciplines.",
    value: "Operator peer network",
    cost: "Free",
    sourceName: "a16z Build",
    sourceUrl: "https://build.a16z.com/fellowships",
    actionLabel: "Explore",
    tags: ["GTM", "Growth", "a16z"],
    trustSignal:
      "Official a16z Build fellowship page describes eight-week cohorts and open fellowship applications.",
    priority: "evergreen",
  },
  {
    id: "blue-ridge-labs-founder-fellowship",
    title: "Blue Ridge Labs Founder Fellowship",
    organization: "Blue Ridge Labs",
    category: "fellowship",
    format: "Hybrid",
    location: "United States / Brooklyn, NY",
    sectors: ["Social impact", "Economic mobility", "Civic tech", "Health"],
    audience: "Early-stage founders working on economic mobility who have strong problem insight but may not have a prototype yet.",
    summary:
      "Blue Ridge Labs helps social impact founders move from idea to MVP through research, user feedback, product support, mentorship, and showcase access.",
    startDate: "2026-09-01",
    value: "$20,000 stipend for selected Build fellows",
    cost: "Free",
    sourceName: "Robin Hood Blue Ridge Labs",
    sourceUrl: "https://robinhood.org/our-work/blue-ridge-labs/founder-fellowship/",
    actionLabel: "Join interest list",
    tags: ["Impact", "Brooklyn", "MVP"],
    trustSignal:
      "Official Blue Ridge Labs page describes a 20-week fellowship path and a $20,000 stipend for selected fellows advancing to the build phase.",
    priority: "watch",
  },
  {
    id: "backersstage-startup-program",
    title: "BackersStage Startup Program",
    organization: "BackersStage",
    category: "investor",
    format: "Online",
    location: "Global",
    sectors: ["Web3", "AI", "Blockchain", "Pre-seed"],
    audience: "Early-stage Web3 and AI founders raising pre-seed, seed, or Series A and looking for investor exposure.",
    summary:
      "BackersStage reviews early Web3 startups and connects selected founders with global investors, mentors, partners, and curated demo-day surfaces.",
    value: "Investor matching and demo-day access",
    cost: "Free",
    sourceName: "BackersStage",
    sourceUrl: "https://www.backersstage.com/apply",
    actionLabel: "Apply to pitch",
    tags: ["Web3", "AI", "Investor access"],
    trustSignal:
      "Official BackersStage apply page says founders can apply to pitch and be connected with relevant investors across its global network.",
    priority: "evergreen",
  },
  {
    id: "1517-fund-flux-watch",
    title: "1517 Fund + Flux Watch",
    organization: "1517 Fund",
    category: "investor",
    format: "Online",
    location: "North America / Global community",
    sectors: ["Deep tech", "Hardware", "Science", "Student founders"],
    audience: "Unconventional founders, dropouts, students, scientists, and garage builders looking for earliest-stage capital and community.",
    summary:
      "1517 backs founders outside conventional credential paths and periodically runs Flux for moonshot science and frontier technology projects.",
    value: "$100,000 Flux investment path",
    cost: "Equity",
    sourceName: "1517 Fund",
    sourceUrl: "https://www.1517fund.com/",
    actionLabel: "Track openings",
    tags: ["Deep tech", "Unconventional founders", "Flux"],
    trustSignal:
      "1517's official site describes grants, angel-to-seed investments, and a global community; the 2026 Flux deadline has passed, so this stays as a watch item.",
    priority: "watch",
  },
  {
    id: "aws-activate",
    title: "AWS Activate Credits",
    organization: "Amazon Web Services",
    category: "incentive",
    format: "Online",
    location: "Global",
    sectors: ["AI", "Cloud", "Infrastructure"],
    audience: "Pre-Series B startups looking to reduce infrastructure and AI build costs.",
    summary:
      "AWS Activate offers startup credit tiers based on funding stage, including direct credits for bootstrapped founders and larger Activate Portfolio packages.",
    value: "Up to $200,000+ in AWS credits",
    cost: "Credits",
    sourceName: "AWS Startups",
    sourceUrl: "https://aws.amazon.com/startups/credits/",
    actionLabel: "Apply",
    tags: ["Cloud credits", "AI", "Non-dilutive"],
    trustSignal: "Official AWS page lists up to $5,000 for Activate Founders and up to $200,000 for Activate Portfolio.",
    priority: "evergreen",
    featured: true,
  },
  {
    id: "google-cloud-startup-program",
    title: "Google for Startups Cloud Program",
    organization: "Google Cloud",
    category: "incentive",
    format: "Online",
    location: "Global",
    sectors: ["Cloud", "AI", "Firebase", "Infrastructure"],
    audience: "Seed to Series A startups looking for Google Cloud, Firebase, AI, and technical support credits.",
    summary:
      "Google's startup cloud program gives eligible startups cloud credits, AI support, Firebase runway, and Google-wide startup benefits.",
    value: "Up to $350,000 in credits for AI startups",
    cost: "Credits",
    sourceName: "Google Cloud",
    sourceUrl: "https://cloud.google.com/startup",
    actionLabel: "Apply",
    tags: ["Cloud credits", "AI", "Firebase"],
    trustSignal:
      "Official Google Cloud startup page lists up to $200,000 in cloud credits, or up to $350,000 for AI-first startups.",
    priority: "evergreen",
    featured: true,
  },
  {
    id: "microsoft-founders-hub",
    title: "Microsoft for Startups Founders Hub",
    organization: "Microsoft for Startups",
    category: "incentive",
    format: "Online",
    location: "Global",
    sectors: ["Azure", "AI", "Developer tools", "Enterprise"],
    audience: "Founders building on Azure, Microsoft AI tooling, GitHub, or enterprise workflows.",
    summary:
      "Microsoft's startup hub provides technical benefits, Azure credits, AI tooling access, and founder resources for early-stage teams.",
    value: "Azure startup credits and technical benefits",
    cost: "Credits",
    sourceName: "Microsoft for Startups",
    sourceUrl: "https://www.microsoft.com/en-us/startups",
    actionLabel: "Apply",
    tags: ["Azure", "AI", "Founder hub"],
    trustSignal: "Official Microsoft for Startups page describes Azure credits and technical benefits for founders.",
    priority: "evergreen",
  },
  {
    id: "cloudflare-startup-program",
    title: "Cloudflare Startup Program",
    organization: "Cloudflare",
    category: "incentive",
    format: "Online",
    location: "Global",
    sectors: ["Security", "Edge", "Developer tools", "Infrastructure"],
    audience: "Startups that need CDN, Workers, security, observability, and edge infrastructure credits.",
    summary:
      "Cloudflare's startup program gives early teams infrastructure credits, community support, and tiered benefits based on company stage.",
    value: "Up to $350,000 in credits",
    cost: "Credits",
    sourceName: "Cloudflare",
    sourceUrl: "https://www.cloudflare.com/startups/",
    actionLabel: "Apply",
    tags: ["Edge", "Security", "Credits"],
    trustSignal: "Official Cloudflare startup page describes tiered credits, including a $10,000 bootstrapped tier and higher-stage tiers.",
    priority: "evergreen",
    featured: true,
  },
  {
    id: "vercel-startup-credits",
    title: "Vercel for Startups Credits",
    organization: "Vercel",
    category: "incentive",
    format: "Online",
    location: "Global",
    sectors: ["Frontend", "AI apps", "Developer tools", "Hosting"],
    audience: "Startups building web apps, AI products, or frontend-heavy user experiences on Vercel.",
    summary:
      "Vercel's startup program offers credits for Pro usage, deployment, scaling, and AI app infrastructure.",
    value: "Up to $30,000 in credits",
    cost: "Credits",
    sourceName: "Vercel",
    sourceUrl: "https://vercel.com/startups/credits",
    actionLabel: "Apply",
    tags: ["Frontend", "AI apps", "Hosting"],
    trustSignal: "Official Vercel startup credits page says eligible startups can receive up to $30,000 toward the platform.",
    priority: "evergreen",
  },
  {
    id: "neon-startup-program",
    title: "Neon Startup Program",
    organization: "Neon",
    category: "incentive",
    format: "Online",
    location: "Global",
    sectors: ["Postgres", "Database", "Developer tools", "AI apps"],
    audience: "Early-stage teams that want serverless Postgres credits, database branching, and scalable database infrastructure.",
    summary:
      "Neon's startup program supports eligible companies with Postgres credits for serverless databases and developer-first workflows.",
    value: "Up to $100,000 in Neon credits",
    cost: "Credits",
    sourceName: "Neon",
    sourceUrl: "https://neon.com/startups",
    actionLabel: "Apply",
    tags: ["Postgres", "Database credits", "Serverless"],
    trustSignal: "Official Neon startup page advertises $100,000 in credits for eligible startup program applicants.",
    priority: "evergreen",
  },
  {
    id: "elevenlabs-startup-grants",
    title: "ElevenLabs Startup Grants",
    organization: "ElevenLabs",
    category: "incentive",
    format: "Online",
    location: "Global",
    sectors: ["Voice AI", "Agents", "Audio", "AI apps"],
    audience: "Startups building conversational AI agents, voice interfaces, media tools, or audio-first products.",
    summary:
      "ElevenLabs grants give selected startups extended access to AI audio tooling so teams can prototype and launch voice products with less burn.",
    value: "12 months and 33M credits",
    cost: "Credits",
    sourceName: "ElevenLabs",
    sourceUrl: "https://elevenlabs.io/startup-grants",
    actionLabel: "Apply",
    tags: ["Voice AI", "Audio", "AI credits"],
    trustSignal: "Official ElevenLabs startup grants page lists 12 months free and 33M characters for startup grant recipients.",
    priority: "evergreen",
  },
  {
    id: "mongodb-for-startups",
    title: "MongoDB for Startups",
    organization: "MongoDB",
    category: "incentive",
    format: "Online",
    location: "Global",
    sectors: ["Database", "Search", "AI", "Developer tools"],
    audience: "Startups building data-heavy products, AI retrieval features, search, or global applications on MongoDB Atlas.",
    summary:
      "MongoDB for Startups offers Atlas credits, technical guidance, AI data platform support, and ecosystem benefits for eligible startups.",
    value: "Atlas credits and technical guidance",
    cost: "Credits",
    sourceName: "MongoDB",
    sourceUrl: "https://www.mongodb.com/solutions/startups",
    actionLabel: "Apply",
    tags: ["Database", "Atlas", "AI"],
    trustSignal: "Official MongoDB startup page describes expanded credits, hands-on technical support, and startup scaling resources.",
    priority: "evergreen",
  },
  {
    id: "mercury-perks",
    title: "Mercury Perks",
    organization: "Mercury",
    category: "incentive",
    format: "Directory",
    location: "United States",
    sectors: ["Banking", "Credits", "Operations", "Finance"],
    audience: "Startup founders who want a banking-linked perk directory for software, cloud credits, finance, and operational tools.",
    summary:
      "Mercury's perks directory bundles startup software credits and discounts, including AWS and Supabase offers for eligible customers.",
    value: "Curated credits and discounts",
    cost: "Free",
    sourceName: "Mercury",
    sourceUrl: "https://mercury.com/perks",
    actionLabel: "Browse perks",
    tags: ["Banking", "Perks", "Credits"],
    trustSignal: "Official Mercury perks page lists curated startup deals, including AWS credits and Supabase credits.",
    priority: "evergreen",
  },
  {
    id: "hubspot-for-startups",
    title: "HubSpot for Startups",
    organization: "HubSpot",
    category: "incentive",
    format: "Online",
    location: "Global",
    sectors: ["CRM", "Sales", "Marketing", "Customer success"],
    audience: "Startups that need CRM, marketing automation, sales pipeline tooling, and founder GTM education.",
    summary:
      "HubSpot's startup program gives eligible founders deep discounts on HubSpot products plus startup-specific training and community access.",
    value: "30-90% off eligible products",
    cost: "Paid",
    sourceName: "HubSpot",
    sourceUrl: "https://www.hubspot.com/startups",
    actionLabel: "Apply",
    tags: ["CRM", "GTM", "Discount"],
    trustSignal: "Official HubSpot for Startups page describes 30-90% startup discounts, training, and founder community benefits.",
    priority: "evergreen",
  },
  {
    id: "stripe-startups",
    title: "Stripe Startups",
    organization: "Stripe",
    category: "incentive",
    format: "Online",
    location: "Global",
    sectors: ["Payments", "Fintech", "Operations", "Revenue"],
    audience: "Venture-backed startups preparing payments, billing, fintech workflows, or marketplace infrastructure.",
    summary:
      "Stripe's startup program gives eligible early-stage startups financial benefits, fee credits or waived processing, expert resources, and community access.",
    value: "Fee credits and startup offers",
    cost: "Credits",
    sourceName: "Stripe",
    sourceUrl: "https://stripe.com/startups",
    actionLabel: "Apply",
    tags: ["Payments", "Fee credits", "Venture-backed"],
    trustSignal: "Official Stripe Startups page describes financial benefits, offers, community, and expert resources for venture-backed startups.",
    priority: "evergreen",
  },
  {
    id: "notion-for-startups",
    title: "Notion for Startups",
    organization: "Notion",
    category: "incentive",
    format: "Online",
    location: "Global",
    sectors: ["Productivity", "AI workspace", "Knowledge base", "Ops"],
    audience: "Founding teams consolidating docs, wiki, project management, AI notes, and operating rhythm in one workspace.",
    summary:
      "Notion gives eligible startups free Business Plan access with Notion AI so early teams can reduce tooling cost and centralize work.",
    value: "Up to 6 months free",
    cost: "Credits",
    sourceName: "Notion",
    sourceUrl: "https://www.notion.com/startups",
    actionLabel: "Apply",
    tags: ["Workspace", "AI", "Team ops"],
    trustSignal: "Official Notion startup page says eligible startups can get Business Plan free for up to 6 months.",
    priority: "evergreen",
  },
  {
    id: "digitalocean-startups",
    title: "DigitalOcean Startups",
    organization: "DigitalOcean",
    category: "incentive",
    format: "Online",
    location: "Global",
    sectors: ["Cloud", "Compute", "Databases", "AI infrastructure"],
    audience: "Early teams that want approachable cloud credits for web apps, databases, app hosting, and lightweight infrastructure.",
    summary:
      "DigitalOcean's startup program supports early teams with cloud credits, startup resources, and founder-friendly infrastructure guidance.",
    value: "Cloud credits and startup support",
    cost: "Credits",
    sourceName: "DigitalOcean",
    sourceUrl: "https://www.digitalocean.com/startups",
    actionLabel: "Apply",
    tags: ["Cloud credits", "Infrastructure", "Startup support"],
    trustSignal: "Official DigitalOcean startups page describes startup credits, usage coverage, and program support details.",
    priority: "evergreen",
  },
  {
    id: "nsf-sbir-2026",
    title: "NSF SBIR/STTR Full Proposal",
    organization: "U.S. National Science Foundation",
    category: "funding",
    format: "Online",
    location: "United States",
    sectors: ["Deep tech", "Science", "Engineering", "AI"],
    audience: "U.S. startups with technical risk and R&D-heavy commercialization plans.",
    summary:
      "NSF SBIR/STTR funding supports early-stage deep-tech R&D. Full proposal deadlines are listed for July and November 2026.",
    deadline: "2026-07-27",
    value: "Non-dilutive R&D funding",
    cost: "Non-dilutive",
    sourceName: "NSF SBIR",
    sourceUrl: "https://seedfund.nsf.gov/apply/full-proposal/",
    actionLabel: "Prepare proposal",
    tags: ["Grant", "Deep tech", "US"],
    trustSignal: "Official NSF SBIR page lists July 27, 2026 and November 4, 2026 full proposal deadlines.",
    priority: "soon",
  },
  {
    id: "metro-east-startup-challenge",
    title: "Metro East Start-Up Challenge 2026",
    organization: "SIUE Illinois SBDC",
    category: "competition",
    format: "Hybrid",
    location: "Metro East Illinois",
    sectors: ["Local business", "Services", "Consumer"],
    audience: "Eligible early ventures in the Metro East Illinois county region.",
    summary:
      "A regional business plan competition with mentorship, cash prizes, and professional services for local entrepreneurs.",
    deadline: "2026-08-09",
    value: "$10,000 first prize + services",
    cost: "Free",
    sourceName: "The Intelligencer",
    sourceUrl: "https://www.theintelligencer.com/news/article/metro-east-il-start-up-challenge-2026-22308060.php",
    actionLabel: "Review",
    tags: ["Pitch", "Local", "Business plan"],
    trustSignal: "Local report says applications opened June 14, 2026 and close August 9, 2026.",
    priority: "soon",
  },
  {
    id: "techcrunch-disrupt-2026",
    title: "TechCrunch Disrupt 2026",
    organization: "TechCrunch",
    category: "conference",
    format: "In-person",
    location: "San Francisco, CA",
    sectors: ["AI", "Fundraising", "DevTools", "Climate", "Fintech"],
    audience: "Founders seeking investor rooms, startup growth sessions, press exposure, and ecosystem access.",
    summary:
      "A major startup conference in San Francisco with founder, investor, and operator programming plus Startup Battlefield exposure.",
    startDate: "2026-10-13",
    endDate: "2026-10-15",
    value: "10,000+ attendees",
    cost: "Paid",
    sourceName: "TechCrunch",
    sourceUrl: "https://techcrunch.com/events/techcrunch-disrupt/",
    actionLabel: "Register",
    tags: ["Conference", "Investors", "SF"],
    trustSignal: "Official TechCrunch page lists October 13-15, 2026 in San Francisco.",
    priority: "watch",
  },
  {
    id: "web-summit-2026",
    title: "Web Summit 2026",
    organization: "Web Summit",
    category: "conference",
    format: "In-person",
    location: "Lisbon, Portugal",
    sectors: ["Global tech", "Startups", "Investors", "Media"],
    audience: "Founders looking for international startup exposure, investor meetings, and startup programming.",
    summary:
      "Web Summit returns to Lisbon with startup programming, investor access, media surfaces, and partner opportunities.",
    startDate: "2026-11-09",
    endDate: "2026-11-12",
    value: "Global startup programme",
    cost: "Paid",
    sourceName: "Web Summit",
    sourceUrl: "https://websummit.com/",
    actionLabel: "Explore",
    tags: ["Conference", "Global", "Startup programme"],
    trustSignal: "Official Web Summit page lists November 9-12, 2026 in Lisbon.",
    priority: "watch",
  },
  {
    id: "slush-2026",
    title: "Slush 2026",
    organization: "Slush",
    category: "conference",
    format: "In-person",
    location: "Helsinki, Finland",
    sectors: ["Startups", "VC", "Europe", "AI"],
    audience: "Founders looking for curated investor meetings, side events, and hands-on company-building advice.",
    summary:
      "A founder-focused startup event in Helsinki with investor day, meeting tools, side events, and strong European ecosystem density.",
    startDate: "2026-11-18",
    endDate: "2026-11-19",
    value: "20,000+ meetings",
    cost: "Paid",
    sourceName: "Slush",
    sourceUrl: "https://slush.org/",
    actionLabel: "Pre-register",
    tags: ["Conference", "VC", "Europe"],
    trustSignal: "Official Slush page lists November 18-19, 2026 in Helsinki.",
    priority: "watch",
  },
  {
    id: "startup-world-cup",
    title: "Startup World Cup",
    organization: "Pegasus Tech Ventures",
    category: "competition",
    format: "Hybrid",
    location: "Global regionals",
    sectors: ["All sectors", "Pitch", "Fundraising"],
    audience: "Startups seeking regional pitch exposure and a path to the global finale.",
    summary:
      "A global pitch competition with regional events across continents and a high-visibility Silicon Valley finale.",
    value: "$1,000,000 investment prize path",
    cost: "Free",
    sourceName: "Startup World Cup",
    sourceUrl: "https://www.startupworldcup.io/",
    actionLabel: "Find regionals",
    tags: ["Pitch", "Competition", "Investors"],
    trustSignal: "Official Startup World Cup site describes 100+ regional competitions across six continents.",
    priority: "watch",
  },
  {
    id: "openai-devday-2026",
    title: "OpenAI DevDay 2026",
    organization: "OpenAI",
    category: "conference",
    format: "In-person",
    location: "San Francisco, CA",
    sectors: ["AI", "Developer tools", "Startups", "Agents"],
    audience: "AI founders, developers, researchers, and startup teams building on frontier models and developer tooling.",
    summary:
      "OpenAI DevDay is a major developer conference for product launches, technical sessions, ecosystem networking, and startup signal around OpenAI's platform.",
    startDate: "2026-09-29",
    value: "Developer ecosystem access",
    cost: "Paid",
    sourceName: "OpenAI",
    sourceUrl: "https://openai.com/index/devday-2026/",
    actionLabel: "Get notified",
    tags: ["AI", "Conference", "SF"],
    trustSignal:
      "Official OpenAI DevDay page lists September 29, 2026 in San Francisco and lets interested attendees sign up for application reminders.",
    priority: "watch",
  },
  {
    id: "product-hunt-launch",
    title: "Product Hunt Launch",
    organization: "Product Hunt",
    category: "launch",
    format: "Online",
    location: "Global",
    sectors: ["SaaS", "Consumer", "AI", "DevTools"],
    audience: "Founders preparing a launch day, community feedback loop, and early-adopter discovery surface.",
    summary:
      "A launch channel and guide for preparing assets, timing, goals, community participation, and product storytelling.",
    value: "Daily launch audience",
    cost: "Community",
    sourceName: "Product Hunt",
    sourceUrl: "https://www.producthunt.com/launch",
    actionLabel: "Plan launch",
    tags: ["Launch", "Community", "Feedback"],
    trustSignal: "Official Product Hunt launch guide.",
    priority: "evergreen",
    featured: true,
  },
  {
    id: "show-hn",
    title: "Show HN",
    organization: "Hacker News",
    category: "launch",
    format: "Online",
    location: "Global",
    sectors: ["DevTools", "AI", "Infrastructure", "Technical products"],
    audience: "Technical founders who want honest early feedback from builders and operators.",
    summary:
      "A high-signal public feedback channel for demos, technical products, open-source projects, and founder launches.",
    value: "Technical founder feedback",
    cost: "Community",
    sourceName: "Hacker News",
    sourceUrl: "https://news.ycombinator.com/show",
    actionLabel: "Browse",
    tags: ["Launch", "Feedback", "Technical"],
    trustSignal: "Official Hacker News Show page.",
    priority: "evergreen",
  },
  {
    id: "launch-hn",
    title: "Launch HN",
    organization: "Y Combinator / Hacker News",
    category: "launch",
    format: "Online",
    location: "YC companies",
    sectors: ["YC startups", "Technical products"],
    audience: "YC startups preparing a curated Hacker News launch.",
    summary:
      "A curated launch path for YC companies where the HN team helps craft a launch post and reviews submissions.",
    value: "Curated YC launch surface",
    cost: "Community",
    sourceName: "Hacker News",
    sourceUrl: "https://news.ycombinator.com/yli.html",
    actionLabel: "Read instructions",
    tags: ["YC", "Launch", "HN"],
    trustSignal: "Official Launch HN instructions page.",
    priority: "evergreen",
  },
  {
    id: "yc-work-at-startup",
    title: "Work at a Startup",
    organization: "Y Combinator",
    category: "talent",
    format: "Online",
    location: "Global / Remote",
    sectors: ["Hiring", "Engineering", "Design", "Sales"],
    audience: "Founders hiring from startup-ready candidates or benchmarking YC hiring demand.",
    summary:
      "YC's startup jobs platform lets candidates create a single profile and browse thousands of startup roles.",
    value: "6,000+ YC startup roles surfaced in June 2026",
    cost: "Free",
    sourceName: "Y Combinator Jobs",
    sourceUrl: "https://www.ycombinator.com/jobs",
    actionLabel: "Browse",
    tags: ["Hiring", "Startup jobs", "YC"],
    trustSignal: "YC jobs page says candidates can apply with a single profile and lists thousands of startup roles.",
    priority: "evergreen",
  },
  {
    id: "github-education",
    title: "GitHub Student Developer Pack",
    organization: "GitHub Education",
    category: "talent",
    format: "Online",
    location: "Students worldwide",
    sectors: ["Students", "Developer tools", "Cloud credits"],
    audience: "Student founders, interns, and campus builders who need discounted or free developer tooling.",
    summary:
      "A student resource bundle with developer tools, cloud hosting, learning resources, and partner offers that can lower early build costs.",
    value: "Dozens of partner offers",
    cost: "Free",
    sourceName: "GitHub Education",
    sourceUrl: "https://education.github.com/pack",
    actionLabel: "Verify student status",
    tags: ["Students", "Tools", "Credits"],
    trustSignal: "Official GitHub Education page describes the Student Developer Pack and eligibility.",
    priority: "evergreen",
  },
  {
    id: "wellfound-startup-talent",
    title: "Wellfound Startup Talent",
    organization: "Wellfound",
    category: "talent",
    format: "Directory",
    location: "Global / Remote",
    sectors: ["Startup jobs", "Internships", "Engineering", "GTM"],
    audience: "Founders hiring startup-ready candidates or students and operators looking for startup roles with salary and equity context.",
    summary:
      "Wellfound is a startup talent marketplace for remote and local roles across engineering, product, design, marketing, sales, and operations.",
    value: "100,000+ startup-ready candidates and jobs",
    cost: "Free",
    sourceName: "Wellfound",
    sourceUrl: "https://wellfound.com/jobs",
    actionLabel: "Browse talent",
    tags: ["Startup jobs", "Remote", "Hiring"],
    trustSignal:
      "Official Wellfound pages describe startup and remote job search, salary and equity visibility, and a large startup talent marketplace.",
    priority: "evergreen",
  },
  {
    id: "we-work-remotely-startup-hiring",
    title: "We Work Remotely",
    organization: "We Work Remotely",
    category: "talent",
    format: "Directory",
    location: "Remote",
    sectors: ["Remote work", "Engineering", "Design", "Product", "Support"],
    audience: "Founders building distributed teams and candidates looking for remote startup and tech roles.",
    summary:
      "We Work Remotely is a remote job board with category filters for programming, design, product, customer support, sales, and marketing.",
    value: "Remote hiring channel",
    cost: "Community",
    sourceName: "We Work Remotely",
    sourceUrl: "https://weworkremotely.com/",
    actionLabel: "Browse jobs",
    tags: ["Remote", "Hiring", "Job board"],
    trustSignal:
      "Official We Work Remotely pages expose remote job categories and search filters across common startup roles.",
    priority: "evergreen",
  },
  {
    id: "techstars-mentors",
    title: "Techstars Mentor Network",
    organization: "Techstars",
    category: "mentor",
    format: "Hybrid",
    location: "Global programs",
    sectors: ["Mentorship", "GTM", "Fundraising", "Product"],
    audience: "Founders who want structured mentor density through accelerator participation or ecosystem programs.",
    summary:
      "Techstars programs combine small classes with mentorship, capital access, and a global network for founders.",
    value: "1,100+ active accelerator mentors",
    cost: "Equity",
    sourceName: "Techstars",
    sourceUrl: "https://www.techstars.com/accelerator-hub",
    actionLabel: "Explore mentors",
    tags: ["Mentors", "Accelerator", "Network"],
    trustSignal: "Official Techstars accelerator hub highlights active mentors and accelerator support.",
    priority: "watch",
  },
  {
    id: "yc-founder-directory",
    title: "YC Founder + Startup Directory",
    organization: "Y Combinator",
    category: "investor",
    format: "Directory",
    location: "Global",
    sectors: ["Investors", "Founder network", "Market maps"],
    audience: "Founders mapping comparable companies, warm paths, and investor-facing narratives.",
    summary:
      "YC's public startup and founder directories help founders research comparable companies and ecosystem relationships.",
    value: "Public YC ecosystem map",
    cost: "Free",
    sourceName: "Y Combinator",
    sourceUrl: "https://www.ycombinator.com/companies",
    actionLabel: "Research",
    tags: ["Investors", "Market map", "YC"],
    trustSignal: "Official YC directory surfaces companies, founders, jobs, and Launch YC resources.",
    priority: "evergreen",
  },
  {
    id: "openvc-investor-database",
    title: "OpenVC Investor Database",
    organization: "OpenVC",
    category: "investor",
    format: "Directory",
    location: "Global",
    sectors: ["Pre-seed", "Seed", "SaaS", "AI", "Fintech"],
    audience: "Founders building targeted fundraising lists and tracking outreach without relying only on warm intros.",
    summary:
      "OpenVC gives founders a searchable fundraising platform with verified investors, direct application paths, and CRM-style pipeline support.",
    value: "20,000+ verified investors",
    cost: "Free",
    sourceName: "OpenVC",
    sourceUrl: "https://www.openvc.app/",
    actionLabel: "Find investors",
    tags: ["Investor database", "Fundraising", "CRM"],
    trustSignal:
      "Official OpenVC page describes a free fundraising platform with 20,000+ verified investors across VCs, angels, family offices, and accelerators.",
    priority: "evergreen",
    featured: true,
  },
  {
    id: "nfx-signal-investor-network",
    title: "NFX Signal",
    organization: "NFX Signal",
    category: "investor",
    format: "Directory",
    location: "Global",
    sectors: ["Pre-seed", "Seed", "Marketplaces", "Network effects"],
    audience: "Founders looking for relevant investors and the strongest possible intro paths into those investors.",
    summary:
      "Signal maps founders, investors, scouts, and angels so startups can search investors and understand potential warm intro paths.",
    value: "3,000+ investors",
    cost: "Free",
    sourceName: "NFX Signal",
    sourceUrl: "https://signal.nfx.com/",
    actionLabel: "Search investors",
    tags: ["Warm intros", "Seed", "Investor graph"],
    trustSignal:
      "Official Signal page says it is a free tool for founders to find the right investors and strongest intro paths.",
    priority: "evergreen",
  },
  {
    id: "openvc-web3-investors",
    title: "OpenVC Web3 Investor List",
    organization: "OpenVC",
    category: "investor",
    format: "Directory",
    location: "Global",
    sectors: ["Web3", "Crypto", "Blockchain", "Infrastructure"],
    audience: "Crypto and Web3 founders who need a cleaner investor starting point than scattered X threads.",
    summary:
      "OpenVC's Web3 investor list helps founders identify crypto-native VCs, Web3-active generalist funds, angels, and ecosystem funding paths.",
    value: "Web3 investor map",
    cost: "Free",
    sourceName: "OpenVC",
    sourceUrl: "https://www.openvc.app/investor-lists/web3-investors",
    actionLabel: "Map Web3 investors",
    tags: ["Web3", "Crypto", "Investor list"],
    trustSignal:
      "Official OpenVC Web3 list names crypto-native and generalist Web3 funding categories for founders preparing outreach.",
    priority: "evergreen",
  },
  {
    id: "product-hunt-news",
    title: "Product Hunt News + Stories",
    organization: "Product Hunt",
    category: "news",
    format: "Online",
    location: "Global",
    sectors: ["Consumer", "SaaS", "AI", "Creator tools"],
    audience: "Founders tracking what is launching, which categories are active, and how makers frame products.",
    summary:
      "Daily product launches, maker stories, and product trend signals for founders calibrating positioning and launch timing.",
    value: "Daily product trend pulse",
    cost: "Community",
    sourceName: "Product Hunt",
    sourceUrl: "https://www.producthunt.com/",
    actionLabel: "Track launches",
    tags: ["News", "Launches", "Trend signal"],
    trustSignal: "Official Product Hunt home surfaces daily launches, news, forums, and launch resources.",
    priority: "evergreen",
  },
  {
    id: "github-trending-repositories",
    title: "GitHub Trending Repositories",
    organization: "GitHub",
    category: "news",
    format: "Directory",
    location: "Global",
    sectors: ["Open source", "AI", "Developer tools", "Infrastructure"],
    audience: "Technical founders scouting open-source projects, AI tools, developer workflows, and fast-rising repository momentum.",
    summary:
      "GitHub Trending is a live signal surface for repositories gaining attention, useful for spotting emerging infrastructure, agent tools, and builder adoption.",
    value: "Daily and weekly open-source signal",
    cost: "Community",
    sourceName: "GitHub Trending",
    sourceUrl: "https://github.com/trending",
    actionLabel: "Track repos",
    tags: ["Open source", "Trending", "Developer signal"],
    trustSignal: "Official GitHub Trending page surfaces repositories gaining community attention across languages and time windows.",
    priority: "evergreen",
    featured: true,
  },
  {
    id: "github-explore",
    title: "GitHub Explore",
    organization: "GitHub",
    category: "news",
    format: "Directory",
    location: "Global",
    sectors: ["Open source", "Developer tools", "AI", "Learning"],
    audience: "Founders and engineers looking for curated GitHub projects, community collections, and technical trend surfaces.",
    summary:
      "GitHub Explore curates trending projects, topic collections, and community recommendations that can help founders spot where builders are moving.",
    value: "Curated technical discovery",
    cost: "Community",
    sourceName: "GitHub Explore",
    sourceUrl: "https://github.com/explore",
    actionLabel: "Explore",
    tags: ["Open source", "Collections", "Technical signal"],
    trustSignal: "Official GitHub Explore describes itself as a guide to trending projects and the GitHub community.",
    priority: "evergreen",
  },
  {
    id: "product-hunt-daily-launches",
    title: "Product Hunt Daily Launches",
    organization: "Product Hunt",
    category: "launch",
    format: "Online",
    location: "Global",
    sectors: ["SaaS", "AI", "Consumer", "Creator tools"],
    audience: "Founders tracking launch positioning, competitor categories, product copy, and launch-day community response.",
    summary:
      "Daily Product Hunt launches give founders a read on what makers are shipping, how products are positioned, and where early users are responding.",
    value: "Daily launch and competitor signal",
    cost: "Community",
    sourceName: "Product Hunt",
    sourceUrl: "https://www.producthunt.com/",
    actionLabel: "Track launches",
    tags: ["Launches", "Competitors", "Positioning"],
    trustSignal: "Product Hunt is the official launch surface; its API documentation also describes a GraphQL API for Product Hunt data.",
    priority: "evergreen",
  },
  {
    id: "reddit-founder-signal-watch",
    title: "Reddit Founder Signal Watch",
    organization: "Reddit",
    category: "forum",
    format: "Directory",
    location: "Online communities",
    sectors: ["Customer discovery", "Startups", "SaaS", "Indie hackers"],
    audience: "Founders looking for weekly pains, launch feedback, competitor complaints, pricing questions, and community distribution ideas.",
    summary:
      "A watchlist for high-signal startup subreddits such as r/startups, r/SaaS, r/Entrepreneur, r/indiehackers, r/ProductHunters, and r/ycombinator.",
    value: "Weekly community pain and trend signal",
    cost: "Community",
    sourceName: "Reddit",
    sourceUrl: "https://www.reddit.com/r/startups/top/?t=week",
    actionLabel: "Review top posts",
    tags: ["Reddit", "Customer discovery", "Weekly signal"],
    trustSignal: "Reddit subreddit top/week pages expose current community discussions; production ingestion should use compliant Reddit API access.",
    priority: "evergreen",
  },
  {
    id: "hacker-news-search-signal",
    title: "Hacker News Search Signal",
    organization: "Hacker News / Algolia",
    category: "news",
    format: "Online",
    location: "Global",
    sectors: ["Developer tools", "AI", "Startups", "Technical products"],
    audience: "Technical founders tracking Show HN launches, Ask HN pain points, launch comments, and developer-adjacent market conversations.",
    summary:
      "HN Search powered by Algolia gives a programmable way to track Show HN, Ask HN, jobs, comments, and founder-relevant technical conversations.",
    value: "Searchable HN market signal",
    cost: "Community",
    sourceName: "HN Search",
    sourceUrl: "https://hn.algolia.com/api",
    actionLabel: "Read API",
    tags: ["Hacker News", "Show HN", "API"],
    trustSignal: "HN Search API documentation describes REST access to Hacker News data through Algolia-powered endpoints.",
    priority: "evergreen",
  },
  {
    id: "founder-forums",
    title: "Founder Community Watchlist",
    organization: "FounderReach",
    category: "forum",
    format: "Directory",
    location: "Online communities",
    sectors: ["Indie hackers", "Startups", "AI builders"],
    audience: "Founders looking for places to recruit beta users, ask questions, and earn trust before launch.",
    summary:
      "A maintained internal watchlist for founder forums: Indie Hackers, relevant Reddit communities, Slack/Discord groups, Product Hunt discussions, and Hacker News.",
    value: "Community distribution map",
    cost: "Community",
    sourceName: "FounderReach research layer",
    sourceUrl: "https://hacklist.io/",
    actionLabel: "Open watchlist",
    tags: ["Forums", "Community", "Distribution"],
    trustSignal: "Seeded from launch-channel research and built to accept community submissions.",
    priority: "evergreen",
  },
];

export const opportunityStats = {
  scrapedAt: "2026-06-20",
  hacklistActiveCount: 32,
  hacklistPrizePool: "$3,519,074",
  activeItems: opportunities.length,
};

export function getOpportunityDate(opportunity: Opportunity) {
  return opportunity.deadline ?? opportunity.startDate ?? opportunity.endDate ?? "";
}

export function getDaysUntil(dateValue?: string) {
  if (!dateValue) return null;

  const now = new Date("2026-06-20T12:00:00-04:00");
  const target = new Date(`${dateValue}T12:00:00-04:00`);
  const diff = target.getTime() - now.getTime();

  return Math.ceil(diff / (1000 * 60 * 60 * 24));
}

export function formatOpportunityDate(dateValue?: string) {
  if (!dateValue) return "Rolling";

  return new Intl.DateTimeFormat("en", {
    month: "short",
    day: "numeric",
    year: "numeric",
  }).format(new Date(`${dateValue}T12:00:00-04:00`));
}

export function getTimingLabel(opportunity: Opportunity) {
  const dateValue = getOpportunityDate(opportunity);
  const daysUntil = getDaysUntil(dateValue);

  if (daysUntil === null) return "Rolling";
  if (daysUntil < 0) return "Recently passed";
  if (daysUntil === 0) return "Today";
  if (daysUntil === 1) return "1 day left";
  return `${daysUntil} days left`;
}

export function sortOpportunitiesByUrgency(items: Opportunity[]) {
  return [...items].sort((a, b) => {
    const aDate = getOpportunityDate(a);
    const bDate = getOpportunityDate(b);
    if (!aDate && !bDate) return a.title.localeCompare(b.title);
    if (!aDate) return 1;
    if (!bDate) return -1;
    return new Date(aDate).getTime() - new Date(bDate).getTime();
  });
}
